version: '3.8'

services:
  db:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    ports:
    - 5432:5432
    volumes:
    - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
  app:
    image: snippetbox
    container_name: application
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 8989:8989

